# Generated by Django 4.0.3 on 2022-05-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
