# Generated by Django 4.0.3 on 2022-05-08 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('room_type', models.CharField(max_length=50)),
                ('room_amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Daily Continental Breakfast', 'Daily Continental Breakfast'), ('Access to fitness room', 'Access to fitness room'), ('Access to Swimming Pool and Jacuzzi', 'Access to Swimming Pool and Jacuzzi'), ('Daily Parking', 'Daily Parking'), ('All meals included', 'All meals included')], default='Daily Parking', max_length=119)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField(default=300.0)),
                ('no_of_days_advance', models.IntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('room_location', models.CharField(default='sanjose', max_length=50)),
                ('room_image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.IntegerField(default=1)),
                ('booking_amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Daily Continental Breakfast', 'Daily Continental Breakfast'), ('Access to fitness room', 'Access to fitness room'), ('Access to Swimming Pool and Jacuzzi', 'Access to Swimming Pool and Jacuzzi'), ('Daily Parking', 'Daily Parking'), ('All meals included', 'All meals included')], default='Daily Parking', max_length=119)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('amount', models.FloatField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
