# Generated by Django 4.0.3 on 2022-04-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_alter_customer_address_alter_customer_pin_code_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
